export const CHANGE_ACTIVE_BUTTON = 'CHANGE_ACTIVE_BUTTON/GAME';

export const CHANGE_NAME_START_BUTTON = 'CHANGE_NAME_START_BUTTON/GAME';

export const ADD_ITEM_ARR_STEP_GAME = 'ADD_ITEM_ARR_STEP_GAME/GAME';

export const CLEAR_ARR_STEP_GAME = 'CLEAR_ARR_STEP_GAME/GAME';

export const CLEAR_STATE = 'CLEAR_STATE/GAME_START_TRY';